app/recepcion/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'recepcion'

urlpatterns = [
    path('proveedores/nuevo/', ProveedorCreate.as_view(), name='ProveedorCreate'),
    path('proveedores/listado/', ProveedorList.as_view(), name='ProveedorList'),
    path('actualizar_proveedor/<int:pk>/', ProveedorUpdate.as_view(), name="ProveedorUpdate"),
    path('eliminar_proveedor/<int:pk>/', ProveedorDelete.as_view(), name="ProveedorDelete"),
    path('datos/proveedor/<int:pk>/', ProveedorDetailView.as_view(), name="ProveedorDetail"),
    
    path('recepcion_manual/nuevo/', RecepcionManualCreate.as_view(), name='RecepcionManualCreate'),
    path('recepcion_manual/listado/', RecepcionManualList.as_view(), name='RecepcionManualList'),
    path('editar/recepcion_manual/<int:pk>/', RecepcionManualUpdate.as_view(), name="RecepcionManualUpdate"),
    path('detalle/recepcion_manual/<int:pk>/', RecepcionManualDetail.as_view(), name="RecepcionManualDetail"),
    path('eliminar_recepcion_manual/<int:pk>/', RecepcionManualDeleteFormView.as_view(), name="RecepcionManualDeleteFormView"),
    
    path('recepcion_gs1', views.recepcion_gs1, name="recepcion_gs1"),
    path('parse_gs1_128', views.parse_gs1_128, name="parse_gs1_128"),
    
    path('tipo_de_merma/nuevo/', TipoDeMermaCreate.as_view(), name='TipoDeMermaCreate'),
    path('tipo_de_merma/listado/', TipoDeMermaList.as_view(), name='TipoDeMermaList'),
    path('actualizar_tipo_de_merma/<int:pk>/', TipoDeMermaUpdate.as_view(), name="TipoDeMermaUpdate"),
    path('eliminar_tipo_de_merma/<int:pk>/', TipoDeMermaDelete.as_view(), name="TipoDeMermaDelete"),
    
    path('mermas/nuevo/', MermasCreate.as_view(), name='MermasCreate'),
    path('mermas/listado/', MermasList.as_view(), name='MermasList'),
    path('actualizar_mermas/<int:pk>/', MermasUpdate.as_view(), name="MermasUpdate"),
    path('eliminar_mermas/<int:pk>/', MermasDelete.as_view(), name="MermasDelete"),
    path('datos/mermas/<int:pk>/', MermasDetailView.as_view(), name="MermasDetailView"),
    
    path('lista_ajustes/', AjusteInventarioList.as_view(), name='AjusteInventarioList'),
    path('crear_juste/', AjusteInventarioCreate.as_view(), name='AjusteInventarioCreate'),
    path('actualizar_ajuste/<int:pk>/', AjusteInventarioUpdate.as_view(), name='AjusteInventarioUpdate'),
    path('eliminar_ajuste/<int:pk>/', AjusteInventarioDelete.as_view(), name='AjusteInventarioDelete'),
    
    path('auditoria/listado/', AuditoriaList.as_view(), name='AuditoriaList'),

    
    
]

etiquetadora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.login.urls', namespace='login')),
    path('super/', include('app.super.urls', namespace='super')), 
    path('dashuser/', include('app.dashuser.urls', namespace='dashuser')),
    path('platos/', include('app.platos.urls', namespace='platos')),
    path('recepcion/', include('app.recepcion.urls', namespace='recepcion')),
    path('audit/', include('app.core.urls', namespace='core')),
    path('pedidos/', include('app.pedidos.urls', namespace='pedidos')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/recepcion/models.py
from django.db import models
from django.utils import timezone
from django.db import transaction
from django.db.models import F
from app.dashuser.models import Alimento, UnidadDeMedida
from app.super.models import ModeloBaseCentro, UserProfile


class Proveedor(ModeloBaseCentro):
    nombre = models.CharField(max_length=200, unique=True, verbose_name="Nombre comercial")
    razon_social = models.CharField(max_length=200, blank=True, verbose_name="Razón social")
    cif_nif = models.CharField(max_length=20, blank=True, verbose_name="CIF/NIF")
    direccion = models.CharField(max_length=255, null=True,blank=True, verbose_name="Dirección")
    codigo_postal = models.CharField(max_length=10, blank=True, null=True,verbose_name="Código postal")
    ciudad = models.CharField(max_length=100, blank=True, null=True,verbose_name="Ciudad")
    provincia = models.CharField(max_length=100, blank=True, null=True,verbose_name="Provincia")
    pais = models.CharField(max_length=100, default="España", null=True,verbose_name="País")
    telefono = models.CharField(max_length=50, blank=True, null=True,verbose_name="Teléfono")
    email = models.EmailField(blank=True, null=True,verbose_name="Correo electrónico")
    web = models.URLField(blank=True, null=True,verbose_name="Sitio web")
    persona_contacto = models.CharField(max_length=150, blank=True, null=True,verbose_name="Persona de contacto")
    telefono_contacto = models.CharField(max_length=50, blank=True, null=True,verbose_name="Teléfono de contacto")
    activo = models.BooleanField(default=True, null=True,verbose_name="Proveedor activo")
    fecha_alta = models.DateField(auto_now_add=True, verbose_name="Fecha de alta")
    observaciones = models.TextField(blank=True, null=True, verbose_name="Observaciones")

    class Meta:
        ordering = ['nombre']
        verbose_name = "Proveedor"
        verbose_name_plural = "Proveedores"

    def __str__(self):
        return self.nombre


class Recepcion(ModeloBaseCentro):
    proveedor = models.ForeignKey(Proveedor, on_delete=models.PROTECT, related_name='recepciones', blank=True)
    alimento = models.ForeignKey(Alimento, on_delete=models.PROTECT, related_name='recepciones')
    lote = models.CharField(max_length=50, help_text="Número de lote del proveedor")
    fecha_caducidad = models.DateField()
    cantidad = models.DecimalField(max_digits=10, decimal_places=2, help_text="Cantidad recibida (kg, L, etc.)")
    unidad_compra = models.ForeignKey(UnidadDeMedida, on_delete=models.PROTECT, help_text="Unidad de medida (kg, L, etc.)")
    precio_compra = models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name="Precio compra" )
    observaciones = models.TextField(blank=True, null=True)
    fecha_recepcion = models.DateTimeField(default=timezone.now, editable=False)

    class Meta:
        ordering = ['-fecha_recepcion']
        verbose_name = "Recepción"
        verbose_name_plural = "Recepciones"

    def __str__(self):
        return f"{self.alimento.nombre} - {self.lote} ({self.proveedor.nombre})"

    def actualizar_stock_alimento(self):
        alimento = self.alimento
        cantidad_entrada = self.cantidad

        # 1️⃣ Conversión si unidad_compra != unidad_uso
        if alimento.unidad_compra_id != alimento.unidad_uso_id:
            if alimento.peso_unitario and alimento.peso_unitario > 0:
                cantidad_entrada *= alimento.peso_unitario
            else:
                raise ValueError(
                    f"El alimento '{alimento.nombre}' necesita peso_unitario para convertir entre unidades."
                )

        # 2️⃣ Actualizar stock
        with transaction.atomic():
            # Guardamos stock_actual
            Alimento.objects.filter(pk=alimento.pk).update(
                stock_actual=models.F('stock_actual') + cantidad_entrada
            )
            alimento.refresh_from_db(fields=['stock_actual'])

            # Recalculamos stock_util
            alimento.stock_util = alimento.stock_actual * (alimento.porcentaje_uso / 100)

            # 3️⃣ Actualizar precio_medio
            if not alimento.precio_medio or alimento.precio_medio == 0:
                alimento.precio_medio = self.precio_compra
            else:
                # Media ponderada: (stock_antiguo * precio_medio + cantidad_nueva * precio_compra) / stock_total
                stock_antiguo = alimento.stock_actual - cantidad_entrada
                alimento.precio_medio = (
                    (stock_antiguo * alimento.precio_medio) + (cantidad_entrada * self.precio_compra)
                ) / alimento.stock_actual

            # Guardamos cambios finales
            alimento.save(update_fields=['stock_util', 'precio_medio'])

    
    
class TipoDeMerma(ModeloBaseCentro):
    nombre = models.CharField(max_length=100, verbose_name="Tipo de merma")
    descripcion = models.TextField(blank=True, null=True, verbose_name="Descripción")
    activo = models.BooleanField(default=True, verbose_name="Activo")  # Para activar/desactivar tipos de merma


    class Meta:
        verbose_name = "Tipo de merma"
        verbose_name_plural = "Tipos de mermas"
        ordering = ["nombre"]

    def __str__(self):
        return self.nombre    
    
    
class Merma(ModeloBaseCentro):
    alimento = models.ForeignKey(Alimento, on_delete=models.CASCADE, related_name="mermas")
    tipo_merma = models.ForeignKey(TipoDeMerma, on_delete=models.PROTECT, verbose_name="Tipo de merma")
    cantidad = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Cantidad perdida")
    unidad_medida = models.ForeignKey(UnidadDeMedida, on_delete=models.CASCADE, verbose_name="Unidad de medida")  # o gr, lt, unidades...
    fecha = models.DateTimeField(auto_now_add=True)
    registrado_por = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, null=True, blank=True, related_name="mermas_registradas")
    observaciones = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = "Merma"
        verbose_name_plural = "Mermas"
        ordering = ["-fecha"]

    def __str__(self):
        return f"{self.alimento.nombre} - {self.cantidad} {self.unidad_medida} ({self.tipo_merma})"

    def save(self, *args, **kwargs):
        # Si la merma ya existía, calculamos diferencia
        if self.pk:  
            old_merma = Merma.objects.get(pk=self.pk)
            diferencia = self.cantidad - old_merma.cantidad
        else:
            diferencia = self.cantidad  # Nueva merma → resta la cantidad entera

        super().save(*args, **kwargs)

        # Actualizar stock en base a diferencia
        if diferencia > 0:  # se perdió más cantidad
            self.alimento.stock_actual = max(self.alimento.stock_actual - diferencia, 0)
        elif diferencia < 0:  # se corrigió a menos pérdida → devolvemos stock
            self.alimento.stock_actual += abs(diferencia)

        self.alimento.save()   
        
        
    def eliminar_y_devolver_stock(self):
        """
        Devuelve la cantidad de la merma al stock del alimento
        y elimina la merma de la base de datos.
        """
        with transaction.atomic():
            # actualizar stock atómicamente
            self.alimento.__class__.objects.filter(pk=self.alimento.pk).update(
                stock_actual=F('stock_actual') + self.cantidad
            )
            # borrar la merma
            self.delete()    
            
            
            
            
class AjusteInventario(ModeloBaseCentro):
    alimento = models.ForeignKey(Alimento, on_delete=models.CASCADE)
    stock_sistema = models.DecimalField(max_digits=10, decimal_places=2, editable=False)
    stock_real = models.DecimalField(max_digits=10, decimal_places=2)
    diferencia = models.DecimalField(max_digits=10, decimal_places=2, editable=False)
    comentario = models.TextField(blank=True, null=True)
    fecha = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-fecha']
        verbose_name = 'Ajuste de Inventario'
        verbose_name_plural = 'Ajustes de Inventario'

    def __str__(self):
        return f"{self.alimento.nombre} ({self.fecha.date()} - {self.centro})"
        

templates/recepcion/crear_recepcion_manual.html
<div class="modal-dialog modal-lg" role="document">
  <div class="modal-content">
    <div class="modal-header bg-inverse-success">
      <h2 class="modal-title">Registrar recepción de producto</h2>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
      <div class="container">
        <form method="POST" action="{% url 'recepcion:RecepcionManualCreate' %}">
          {% csrf_token %}
          {{ formset.management_form }}  <!-- MUY IMPORTANTE -->

          <div id="formset-container">
            {% for form in formset %}
              <div class="form-row border p-2 mb-2">
                <div class="row g-3">
                  <div class="col-md-6">
                    <label class="form-label">Proveedor</label>
                    {{ form.proveedor }}
                  </div>
                  <div class="col-md-6">
                    <label class="form-label">Alimento</label>
                    {{ form.alimento }}
                  </div>
                  <div class="col-md-6">
                    <label class="form-label">Lote</label>
                    {{ form.lote }}
                  </div>
                  <div class="col-md-6">
                    <label class="form-label">Fecha de caducidad</label>
                    {{ form.fecha_caducidad }}
                  </div>
                  <div class="col-md-4">
                    <label class="form-label">Cantidad</label>
                    {{ form.cantidad }}
                  </div>
                  <div class="col-md-4">
                    <label class="form-label">Unidad de medida</label>
                    {{ form.unidad_compra }}
                  </div>
                  <div class="col-md-4">
                    <label class="form-label">Precio unidad</label>
                    {{ form.precio_compra }}
                  </div>
                  <div class="col-md-12">
                    <label class="form-label">Observaciones</label>
                    {{ form.observaciones }}
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>

          <button type="button" class="btn btn-success" id="add-form">Añadir otro alimento</button>
          <button type="submit" class="btn btn-info">Guardar todas las recepciones</button>
        </form>
      </div>
    </div>
  </div>
</div>

<script>
  document.getElementById('add-form').addEventListener('click', function() {
      let container = document.getElementById('formset-container');
      let totalForms = parseInt(document.getElementById('id_form-TOTAL_FORMS').value);
      
      let newForm = container.children[0].cloneNode(true);

      // Limpiar los valores
      newForm.querySelectorAll('input, select').forEach(function(input){
          if (input.type != 'hidden') input.value = '';
      });

      // Actualizar índices del formset
      newForm.innerHTML = newForm.innerHTML.replace(/form-0-/g, 'form-' + totalForms + '-');

      container.appendChild(newForm);
      document.getElementById('id_form-TOTAL_FORMS').value = totalForms + 1;
  });


  // cerrar modal al hacer clic en cancelar
  $('.modal .btn-danger').click(function() {
    $('.modal').modal('hide');
    $('.modal-backdrop').remove();
  });
</script>

templates/recepcion/detalle_merma.html
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header bg-warning text-white">
            <h2 class="modal-title">Editar Merma</h2>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
         </div>
        <div class="modal-body">
                <div class="container">
                    <!-- Cambia la URL a la de tu vista de actualización -->
                    <form method="POST" action="{% url 'recepcion:MermasUpdate' merma.id %}">
                        {% csrf_token %}
                        <div class="card-body">
                            <form method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 mb-3">
                                <label for="id_alimento" class="form-label">Alimento</label>
                                {{ form.alimento }}
                                </div>
                                <div class="col-md-6 mb-3">
                                <label for="id_tipo_merma" class="form-label">Tipo de merma</label>
                                {{ form.tipo_merma }}
                                </div>
                                <div class="col-md-6 mb-3">
                                <label for="id_cantidad" class="form-label">Cantidad</label>
                                {{ form.cantidad }}
                                </div>
                                <div class="col-md-6 mb-3">
                                <label for="id_unidad_medida" class="form-label">Unidad de medida</label>
                                {{ form.unidad_medida }}
                                </div>
                                <div class="col-md-12 mb-3">
                                <label for="id_observaciones" class="form-label">Observaciones</label>
                                {{ form.observaciones }}
                                </div>
                            </div>
                            <div class="mt-3 text-end">
                                <button type="submit" class="btn btn-success">Guardar cambios</button>
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
  // cerrar modal al hacer clic en cancelar
  $('.modal .btn-secondary').click(function() {
    $('.modal').modal('hide');
    $('.modal-backdrop').remove();
  });
</script>

templates/recepcion/listar_ajuste.html
{% extends "base.html" %}
{% block content %}

<div class="content-wrapper">
    <div class="card shadow-lg">
        <div class="card-header bg-secondary text-white d-flex justify-content-between align-items-center">
            <h3 class="m-0">Listado de Ajustes del stock</h3>
            <a class="btn btn-light btn-sm rounded text-primary" onclick="abrir_modal_edicion('{% url 'recepcion:AjusteInventarioCreate' %}')">
                <i class="fa fa-plus-circle"></i>&nbsp; Crear Nuevo
            </a>
        </div>

        <div class="card-body mt-3">
            <form method="get" class="row g-2 align-items-center">
                <div class="col-md-11">
                    <input type="text" class="form-control form-control-sm" placeholder="Buscar..." name="buscar">
                </div>
                <div class="col-md-1 d-flex justify-content">
                    <button type="submit" class="btn btn-inverse-secondary btn-md" >
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </form>

            {% if ajustes %}
            <div class="table-wrapper">
                <table class="table table-hover tabla-responsive align-middle">
                    <thead class="table-dark">
                        <tr>
                            <th>Alimento</th>
                            <th>Stock Inicial</th>
                            <th>Stock Real</th>
                            <th>Diferencia</th>
                            <th>Fecha</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ajuste in ajustes %}
                        <tr>
                            <td data-label="Alimento" class="fw-bold">{{ ajuste.alimento }}</td>
                            <td data-label="Stock Inicial">{{ ajuste.stock_sistema}}</td>
                            <td data-label="Stock Real">{{ ajuste.stock_real}}</td>
                            <td data-label="Diferencia">{{ ajuste.diferencia}}</td>
                            <td data-label="Fecha">{{ ajuste.fecha}}</td>
                            <td data-label="Acciones">
                                <a class="btn btn-inverse-info" style="--bs-btn-padding-y: 14px; --bs-btn-padding-x: 14px;" onclick="abrir_modal_edicion('{% url 'recepcion:AjusteInventarioUpdate' ajuste.id %}')" data-toggle="tooltip" title="Editar Merma">
                                    <i class="fa fa-pencil"></i>
                                </a>
                                <a class="btn btn-inverse-danger" style="--bs-btn-padding-y: 14px; --bs-btn-padding-x: 14px;" onclick="abrir_modal_edicion('{% url 'recepcion:AjusteInventarioDelete' ajuste.id %}')" data-toggle="tooltip" title="Eliminar Merma">
                                    <i class="fa fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <!-- Paginación -->
            {% include "core/pagination.html" %}
            
            {% else %}
            <div class="alert alert-warning text-center mt-3">
                <i class="fa fa-exclamation-circle"></i> No se encontraron ajustes en el inventario.
            </div>
            {% endif %}
        </div>
        <div class="modal fade" id="consulta" role="dialog">
    </div>
</div>

{% endblock content %}

{% block extrajs %}
<script type="text/javascript">
    var $ = jQuery.noConflict();
    function abrir_modal_edicion(url){
        $('#consulta').load(url, function(){
            $(this).modal('show');
        });
    }
</script>
{% endblock extrajs %}

templates/recepcion/listar_recepcion_manual.html
{% extends "base.html" %}
{% block content %}

<div class="content-wrapper">
    <div class="card shadow-lg">
        <div class="card-header bg-primary text-white d-flex justify-content-between align-items-center">
            <h3 class="m-0">Listado de recepciones</h3>
            <a class="btn btn-light text-primary" href="{% url 'recepcion:recepcion_gs1' %}">
                <i class="fa fa-plus-circle"></i>&nbsp; Leer código de barras
            </a>
            <a class="btn btn-light text-primary" onclick="abrir_modal_edicion('{% url 'recepcion:RecepcionManualCreate' %}')">
                <i class="fa fa-plus-circle"></i>&nbsp; Recepción Manual
            </a>
        </div>
        <div class="card-body">
            <form method="get" class="row g-2 align-items-center">
                <div class="col-md-4">
                    <select class="form-select" name="ordenar" id="ordenar" onchange="this.form.submit()">
                        <option value="" disabled selected>Ordenar por...</option>
                        <option value="alimento" {% if ordenar == 'alimento' %}selected{% endif %}>Alimento</option>
                        <option value="proveedor" {% if ordenar == 'proveedor' %}selected{% endif %}>Proveedor</option>
                        <option value="lote" {% if ordenar == 'lote' %}selected{% endif %}>Lote</option>
                        <option value="fecha_recepcion" {% if ordenar == 'fecha_recepcion' %}selected{% endif %}>Fecha de recepción</option>
                    </select>
                </div>
                <div class="col-md-5">
                    <input type="text" class="form-control" placeholder="Buscar..." name="buscar">
                </div>
                <div class="col-md-3 d-flex justify-content-end">
                    <button type="submit" class="btn btn-inverse-secondary">
                        <i class="fa fa-search"></i>&nbsp; Buscar
                    </button>
                </div>
            </form>
                {% if recepciones %}
                <div class="table-responsive">
                    <table class="table table-hover align-middle">
                        <thead class="table-dark text-center">
                            <tr>
                                <th>Fecha Recepción</th>
                                <th>Alimento</th>
                                <th>Cantidad</th>
                                <th>Proveedor</th>
                                <td>Lote</td>
                                <th>Opciones</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for recepcion in recepciones %}
                        <tr class="text-center" style="font-size: 14px;">
                            <td>
                                {{ recepcion.fecha_recepcion|date:"d/m/Y H:i" }}
                            </td>
                            <td>{{ recepcion.alimento }}</td>
                            <td>{{ recepcion.cantidad }} {{ recepcion.unidad_medida.abreviatura }}</td>
                            <td>{{ recepcion.proveedor }}</td>
                            <td>{{ recepcion.lote }}</td>
                            <td>
                                <a class="btn btn-inverse-success" style="--bs-btn-padding-y: 10px; --bs-btn-padding-x: 14px;" onclick="abrir_modal_edicion('{% url 'recepcion:RecepcionManualDetail' pk=recepcion.id %}')" data-toggle="tooltip" title="Detalles recepción">
                                    <i class="fa fa-eye"></i>
                                </a>
                                <a class="btn btn-inverse-info" style="--bs-btn-padding-y: 10px; --bs-btn-padding-x: 14px;" onclick="abrir_modal_edicion('{% url 'recepcion:RecepcionManualUpdate' pk=recepcion.id %}')" data-toggle="tooltip" title="Editar recepción">
                                    <i class="fa fa-pencil"></i>
                                </a>
                                <a class="btn btn-inverse-danger" style="--bs-btn-padding-y: 10px; --bs-btn-padding-x: 14px;" onclick="abrir_modal_edicion('{% url 'recepcion:RecepcionManualDeleteFormView' pk=recepcion.id %}')" data-toggle="tooltip" title="Eliminar recepción">
                                    <i class="fa fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <!-- Paginación -->
            {% include "core/pagination.html" %}

            {% else %}
            <div class="alert alert-warning text-center mt-3">
                <i class="fa fa-exclamation-circle"></i> No se encontraron alimentos.
            </div>
            {% endif %}
        </div>
        <div class="modal fade" id="consulta" role="dialog">
    </div>
</div>

{% endblock content %}

{% block extrajs %}
<script type="text/javascript">
    var $ = jQuery.noConflict();
    function abrir_modal_edicion(url){
        $('#consulta').load(url, function(){
            $(this).modal('show');
        });
    }
</script>

{% endblock extrajs %}

templates/recepcion/listar_tipodemerma.html
{% extends "base.html" %}
{% block content %}

<div class="content-wrapper">
    <div class="card shadow-lg">
        <div class="card-header bg-primary text-white d-flex justify-content-between align-items-center">
            <h3 class="m-0">Listado de Tipos de mermas</h3>
            <a class="btn btn-light btn-sm rounded text-primary" onclick="abrir_modal_edicion('{% url 'recepcion:TipoDeMermaCreate' %}')">
                <i class="fa fa-plus-circle"></i>&nbsp; Crear Nuevo
            </a>
        </div>

        <div class="card-body">
            <form method="get" class="row g-2 align-items-center">
                <div class="col-md-11">
                    <input type="text" class="form-control form-control-sm" placeholder="Buscar..." name="buscar">
                </div>
                <div class="col-md-1 d-flex justify-content">
                    <button type="submit" class="btn btn-secondary btn-sm rounded" >
                        <i class="fa fa-search"></i>&nbsp; Buscar
                    </button>
                </div>
            </form>

            {% if tipodemermas %}
            <div class="table-wrapper">
                <table class="table table-hover tabla-responsive align-middle" style="table-layout: fixed;">
                    <thead class="table-dark">
                        <tr>
                            <th>Estado</th>
                            <th>Nombre</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for tipodemerma in tipodemermas %}
                        <tr>
                            <td data-label="Estado">
                                {% if tipodemerma.activo %}
                                    <span class="badge bg-success">Activo</span>
                                {% else %}
                                    <span class="badge bg-danger">Inactivo</span>
                                {% endif %}
                            </td>
                            <td data-label="Nombre" class="fw-bold">{{ tipodemerma.nombre }}</td>
                            <td data-label="Opciones">
                                <a class="btn btn-info" style="--bs-btn-padding-y: 14px; --bs-btn-padding-x: 14px;" onclick="abrir_modal_edicion('{% url 'recepcion:TipoDeMermaUpdate' tipodemerma.id %}')" data-toggle="tooltip" title="Editar Tipo de Alimento">
                                    <i class="fa fa-pencil"></i>
                                </a>
                                <a class="btn btn-danger" style="--bs-btn-padding-y: 14px; --bs-btn-padding-x: 14px;" onclick="abrir_modal_edicion('{% url 'recepcion:TipoDeMermaDelete' tipodemerma.id %}')" data-toggle="tooltip" title="Eliminar Tipo de Alimento">
                                    <i class="fa fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <!-- Paginación -->
            {% include "core/pagination.html" %}

            {% else %}
            <div class="alert alert-warning text-center mt-3">
                <i class="fa fa-exclamation-circle"></i> No se encontraron tipos de merma.
            </div>
            {% endif %}
        </div>
        <div class="modal fade" id="consulta" role="dialog">
    </div>
</div>

{% endblock content %}

{% block extrajs %}
<script type="text/javascript">
    var $ = jQuery.noConflict();
    function abrir_modal_edicion(url){
        $('#consulta').load(url, function(){
            $(this).modal('show');
        });
    }
</script>
{% endblock extrajs %}